Update script collection

diff --git a/script/build-docker b/script/build-docker
--- a/script/build-docker
+++ b/script/build-docker
@@ -20,19 +20,32 @@ else
     DOCKER_REGISTRY_PREFIX="${DOCKER_REGISTRY_HOST}/"
 fi
 
-BRANCH_TAG=${BRANCH_TAG:-latest}
-DEV_IMAGE_TAG="${DOCKER_REGISTRY_PREFIX}kronkltd/jiksnu:${BRANCH_TAG}-dev"
-PRODUCTION_IMAGE_TAG="${DOCKER_REGISTRY_PREFIX}kronkltd/jiksnu:${BRANCH_TAG}"
+ORG=${ORG:-kronkltd}
+PROJECT=${PROJECT:-jiksnu}
+REPOSITORY_NAME=${REPOSITORY_NAME:-${ORG?}/${PROJECT?}}
+
+BRANCH_TAG=${BRANCH_TAG:-$(script/get-branch-tag)}
+IMAGE_TAG="${DOCKER_REGISTRY_PREFIX?}${REPOSITORY_NAME?}:${BRANCH_TAG?}"
+
+DEV_BRANCH_TAG=${DEV_BRANCH_TAG:-${BRANCH_TAG?}-dev}
+DEV_IMAGE_TAG="${DOCKER_REGISTRY_PREFIX?}${REPOSITORY_NAME?}:${DEV_BRANCH_TAG?}"
+
+LATEST_IMAGE_TAG="${DOCKER_REGISTRY_PREFIX?}${REPOSITORY_NAME?}:latest"
+LATEST_DEV_IMAGE_TAG="${DOCKER_REGISTRY_PREFIX?}${REPOSITORY_NAME?}:latest-dev"
 
 echo ">> Pulling Existing Image(s)"
-docker pull $DEV_IMAGE_TAG || \
-  echo >&2 "Could not find existing image ($DEV_IMAGE_TAG). Building anyway."
-docker pull $PRODUCTION_IMAGE_TAG || \
-  echo >&2 "Could not find existing image ($PRODUCTION_IMAGE_TAG). Building anyway."
+docker pull ${LATEST_IMAGE_TAG?} || \
+  echo >&2 "Could not find existing image (${LATEST_IMAGE_TAG?}). Building anyway."
+docker pull ${LATEST_DEV_IMAGE_TAG?} || \
+  echo >&2 "Could not find existing image (${LATEST_DEV_IMAGE_TAG?}). Building anyway."
+docker pull ${DEV_IMAGE_TAG?} || \
+  echo >&2 "Could not find existing image (${DEV_IMAGE_TAG?}). Building anyway."
+docker pull ${IMAGE_TAG?} || \
+  echo >&2 "Could not find existing image (${IMAGE_TAG?}). Building anyway."
 
 echo ">> Building New Image(s)"
-echo "- $DEV_IMAGE_TAG"
-docker build -t $DEV_IMAGE_TAG -f docker/web-dev/Dockerfile .
-echo "- $PRODUCTION_IMAGE_TAG"
+echo "- ${DEV_IMAGE_TAG?}"
+docker build -t ${DEV_IMAGE_TAG?} -f docker/web-dev/Dockerfile .
+echo "- ${IMAGE_TAG?}"
 sigil -p -f Dockerfile.tmpl > Dockerfile
 docker-compose build web
